 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sensor_measurements", type: :request do
  
  # SensorMeasurement. As you add validations to SensorMeasurement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SensorMeasurement.create! valid_attributes
      get sensor_measurements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sensor_measurement = SensorMeasurement.create! valid_attributes
      get sensor_measurement_url(sensor_measurement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sensor_measurement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sensor_measurement = SensorMeasurement.create! valid_attributes
      get edit_sensor_measurement_url(sensor_measurement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SensorMeasurement" do
        expect {
          post sensor_measurements_url, params: { sensor_measurement: valid_attributes }
        }.to change(SensorMeasurement, :count).by(1)
      end

      it "redirects to the created sensor_measurement" do
        post sensor_measurements_url, params: { sensor_measurement: valid_attributes }
        expect(response).to redirect_to(sensor_measurement_url(SensorMeasurement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SensorMeasurement" do
        expect {
          post sensor_measurements_url, params: { sensor_measurement: invalid_attributes }
        }.to change(SensorMeasurement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sensor_measurements_url, params: { sensor_measurement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sensor_measurement" do
        sensor_measurement = SensorMeasurement.create! valid_attributes
        patch sensor_measurement_url(sensor_measurement), params: { sensor_measurement: new_attributes }
        sensor_measurement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sensor_measurement" do
        sensor_measurement = SensorMeasurement.create! valid_attributes
        patch sensor_measurement_url(sensor_measurement), params: { sensor_measurement: new_attributes }
        sensor_measurement.reload
        expect(response).to redirect_to(sensor_measurement_url(sensor_measurement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sensor_measurement = SensorMeasurement.create! valid_attributes
        patch sensor_measurement_url(sensor_measurement), params: { sensor_measurement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sensor_measurement" do
      sensor_measurement = SensorMeasurement.create! valid_attributes
      expect {
        delete sensor_measurement_url(sensor_measurement)
      }.to change(SensorMeasurement, :count).by(-1)
    end

    it "redirects to the sensor_measurements list" do
      sensor_measurement = SensorMeasurement.create! valid_attributes
      delete sensor_measurement_url(sensor_measurement)
      expect(response).to redirect_to(sensor_measurements_url)
    end
  end
end
