 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sensor_models", type: :request do
  
  # SensorModel. As you add validations to SensorModel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SensorModel.create! valid_attributes
      get sensor_models_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sensor_model = SensorModel.create! valid_attributes
      get sensor_model_url(sensor_model)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sensor_model_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sensor_model = SensorModel.create! valid_attributes
      get edit_sensor_model_url(sensor_model)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SensorModel" do
        expect {
          post sensor_models_url, params: { sensor_model: valid_attributes }
        }.to change(SensorModel, :count).by(1)
      end

      it "redirects to the created sensor_model" do
        post sensor_models_url, params: { sensor_model: valid_attributes }
        expect(response).to redirect_to(sensor_model_url(SensorModel.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SensorModel" do
        expect {
          post sensor_models_url, params: { sensor_model: invalid_attributes }
        }.to change(SensorModel, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sensor_models_url, params: { sensor_model: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sensor_model" do
        sensor_model = SensorModel.create! valid_attributes
        patch sensor_model_url(sensor_model), params: { sensor_model: new_attributes }
        sensor_model.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sensor_model" do
        sensor_model = SensorModel.create! valid_attributes
        patch sensor_model_url(sensor_model), params: { sensor_model: new_attributes }
        sensor_model.reload
        expect(response).to redirect_to(sensor_model_url(sensor_model))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sensor_model = SensorModel.create! valid_attributes
        patch sensor_model_url(sensor_model), params: { sensor_model: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sensor_model" do
      sensor_model = SensorModel.create! valid_attributes
      expect {
        delete sensor_model_url(sensor_model)
      }.to change(SensorModel, :count).by(-1)
    end

    it "redirects to the sensor_models list" do
      sensor_model = SensorModel.create! valid_attributes
      delete sensor_model_url(sensor_model)
      expect(response).to redirect_to(sensor_models_url)
    end
  end
end
