 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sensor_manufacturers", type: :request do
  
  # SensorManufacturer. As you add validations to SensorManufacturer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SensorManufacturer.create! valid_attributes
      get sensor_manufacturers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sensor_manufacturer = SensorManufacturer.create! valid_attributes
      get sensor_manufacturer_url(sensor_manufacturer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sensor_manufacturer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      sensor_manufacturer = SensorManufacturer.create! valid_attributes
      get edit_sensor_manufacturer_url(sensor_manufacturer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SensorManufacturer" do
        expect {
          post sensor_manufacturers_url, params: { sensor_manufacturer: valid_attributes }
        }.to change(SensorManufacturer, :count).by(1)
      end

      it "redirects to the created sensor_manufacturer" do
        post sensor_manufacturers_url, params: { sensor_manufacturer: valid_attributes }
        expect(response).to redirect_to(sensor_manufacturer_url(SensorManufacturer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SensorManufacturer" do
        expect {
          post sensor_manufacturers_url, params: { sensor_manufacturer: invalid_attributes }
        }.to change(SensorManufacturer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sensor_manufacturers_url, params: { sensor_manufacturer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sensor_manufacturer" do
        sensor_manufacturer = SensorManufacturer.create! valid_attributes
        patch sensor_manufacturer_url(sensor_manufacturer), params: { sensor_manufacturer: new_attributes }
        sensor_manufacturer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the sensor_manufacturer" do
        sensor_manufacturer = SensorManufacturer.create! valid_attributes
        patch sensor_manufacturer_url(sensor_manufacturer), params: { sensor_manufacturer: new_attributes }
        sensor_manufacturer.reload
        expect(response).to redirect_to(sensor_manufacturer_url(sensor_manufacturer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        sensor_manufacturer = SensorManufacturer.create! valid_attributes
        patch sensor_manufacturer_url(sensor_manufacturer), params: { sensor_manufacturer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sensor_manufacturer" do
      sensor_manufacturer = SensorManufacturer.create! valid_attributes
      expect {
        delete sensor_manufacturer_url(sensor_manufacturer)
      }.to change(SensorManufacturer, :count).by(-1)
    end

    it "redirects to the sensor_manufacturers list" do
      sensor_manufacturer = SensorManufacturer.create! valid_attributes
      delete sensor_manufacturer_url(sensor_manufacturer)
      expect(response).to redirect_to(sensor_manufacturers_url)
    end
  end
end
