 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/vaccination_campaigns", type: :request do
  
  # VaccinationCampaign. As you add validations to VaccinationCampaign, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      VaccinationCampaign.create! valid_attributes
      get vaccination_campaigns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      vaccination_campaign = VaccinationCampaign.create! valid_attributes
      get vaccination_campaign_url(vaccination_campaign)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_vaccination_campaign_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      vaccination_campaign = VaccinationCampaign.create! valid_attributes
      get edit_vaccination_campaign_url(vaccination_campaign)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new VaccinationCampaign" do
        expect {
          post vaccination_campaigns_url, params: { vaccination_campaign: valid_attributes }
        }.to change(VaccinationCampaign, :count).by(1)
      end

      it "redirects to the created vaccination_campaign" do
        post vaccination_campaigns_url, params: { vaccination_campaign: valid_attributes }
        expect(response).to redirect_to(vaccination_campaign_url(VaccinationCampaign.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new VaccinationCampaign" do
        expect {
          post vaccination_campaigns_url, params: { vaccination_campaign: invalid_attributes }
        }.to change(VaccinationCampaign, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post vaccination_campaigns_url, params: { vaccination_campaign: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested vaccination_campaign" do
        vaccination_campaign = VaccinationCampaign.create! valid_attributes
        patch vaccination_campaign_url(vaccination_campaign), params: { vaccination_campaign: new_attributes }
        vaccination_campaign.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the vaccination_campaign" do
        vaccination_campaign = VaccinationCampaign.create! valid_attributes
        patch vaccination_campaign_url(vaccination_campaign), params: { vaccination_campaign: new_attributes }
        vaccination_campaign.reload
        expect(response).to redirect_to(vaccination_campaign_url(vaccination_campaign))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        vaccination_campaign = VaccinationCampaign.create! valid_attributes
        patch vaccination_campaign_url(vaccination_campaign), params: { vaccination_campaign: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested vaccination_campaign" do
      vaccination_campaign = VaccinationCampaign.create! valid_attributes
      expect {
        delete vaccination_campaign_url(vaccination_campaign)
      }.to change(VaccinationCampaign, :count).by(-1)
    end

    it "redirects to the vaccination_campaigns list" do
      vaccination_campaign = VaccinationCampaign.create! valid_attributes
      delete vaccination_campaign_url(vaccination_campaign)
      expect(response).to redirect_to(vaccination_campaigns_url)
    end
  end
end
